# Generated by Django 3.1.1 on 2020-09-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
